name: db-base
channels:
  - conda-forge
  - https://conda.anaconda.org/conda-forge/
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.7.2=h166bdaf_0
  - asttokens=2.0.8=pyhd8ed1ab_0
  - attr=2.5.1=h166bdaf_1
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - brotli=1.0.9=h166bdaf_7
  - brotli-bin=1.0.9=h166bdaf_7
  - brotlipy=0.7.0=py39hb9d737c_1004
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2022.12.7=ha878542_0
  - certifi=2022.12.7=pyhd8ed1ab_0
  - cffi=1.15.1=py39he91dace_0
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - cryptography=37.0.4=py39hd97740a_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - dbus=1.13.6=h5008d03_3
  - debugpy=1.6.3=py39h5a03fae_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - et_xmlfile=1.0.1=py_1001
  - executing=1.0.0=pyhd8ed1ab_0
  - expat=2.4.8=h27087fc_0
  - fftw=3.3.10=nompi_hf0379b8_105
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.0=hc2a2eb6_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.37.2=py39hb9d737c_0
  - freetds=1.1.15=h94af77a_1
  - freetype=2.12.1=hca18f0e_0
  - future=0.18.2=py39hf3d152e_5
  - gettext=0.19.8.1=h73d1719_1008
  - giflib=5.2.1=h36c2ea0_2
  - glib=2.72.1=h6239696_0
  - glib-tools=2.72.1=h6239696_0
  - greenlet=1.1.3=py39h5a03fae_0
  - gst-plugins-base=1.20.3=h57caac4_1
  - gstreamer=1.20.3=hd4edc92_1
  - icu=70.1=h27087fc_0
  - idna=3.3=pyhd8ed1ab_0
  - importlib-metadata=4.11.4=py39hf3d152e_0
  - ipykernel=6.15.1=pyh210e3f2_0
  - ipython=8.5.0=pyh41d4057_1
  - ipython-sql=0.3.9=pyhd8ed1ab_1004
  - ipython_genutils=0.2.0=py_1
  - jack=1.9.18=h8c3723f_1003
  - jedi=0.18.1=pyhd8ed1ab_2
  - jpeg=9e=h166bdaf_2
  - jupyter_client=7.3.5=pyhd8ed1ab_0
  - jupyter_core=4.11.1=py39hf3d152e_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.4=py39hf939315_0
  - krb5=1.19.3=h3790be6_0
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - lerc=4.0.0=h27087fc_0
  - libblas=3.9.0=16_linux64_openblas
  - libbrotlicommon=1.0.9=h166bdaf_7
  - libbrotlidec=1.0.9=h166bdaf_7
  - libbrotlienc=1.0.9=h166bdaf_7
  - libcap=2.65=ha37c62d_0
  - libcblas=3.9.0=16_linux64_openblas
  - libclang=14.0.6=default_h2e3cab8_0
  - libclang13=14.0.6=default_h3a83d3e_0
  - libcups=2.3.3=h3e49a29_2
  - libdb=6.2.32=h9c3ff4c_0
  - libdeflate=1.14=h166bdaf_0
  - libedit=3.1.20191231=he28a2e2_2
  - libevent=2.1.10=h9b69904_4
  - libffi=3.4.2=h7f98852_5
  - libflac=1.3.4=h27087fc_0
  - libgcc-ng=12.1.0=h8d9b700_16
  - libgfortran-ng=12.1.0=h69a702a_16
  - libgfortran5=12.1.0=hdcd56e2_16
  - libglib=2.72.1=h2d90d5f_0
  - libgomp=12.1.0=h8d9b700_16
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=16_linux64_openblas
  - libllvm14=14.0.6=he0ac6c6_0
  - libnsl=2.0.0=h7f98852_0
  - libogg=1.3.4=h7f98852_1
  - libopenblas=0.3.21=pthreads_h78a6416_3
  - libopus=1.3.1=h7f98852_1
  - libpng=1.6.38=h753d276_0
  - libpq=14.5=hd77ab85_0
  - libsndfile=1.0.31=h9c3ff4c_1
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.39.3=h753d276_0
  - libstdcxx-ng=12.1.0=ha89aaad_16
  - libtiff=4.4.0=h55922b4_4
  - libtool=2.4.6=h9c3ff4c_1008
  - libudev1=249=h166bdaf_4
  - libuuid=2.32.1=h7f98852_1000
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp=1.2.4=h522a892_0
  - libwebp-base=1.2.4=h166bdaf_0
  - libxcb=1.13=h7f98852_1004
  - libxkbcommon=1.0.3=he3ba5ed_0
  - libxml2=2.9.14=h22db469_4
  - libzlib=1.2.12=h166bdaf_3
  - lz4-c=1.9.3=h9c3ff4c_1
  - matplotlib-base=3.5.2=py39h700656a_1
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=8.0.30=haf5c9bc_1
  - mysql-libs=8.0.30=h28c427c_1
  - ncurses=6.3=h27087fc_1
  - nest-asyncio=1.5.5=pyhd8ed1ab_0
  - nspr=4.32=h9c3ff4c_1
  - nss=3.78=h2350873_0
  - numpy=1.23.3=py39hba7629e_0
  - openjpeg=2.5.0=h7d73246_1
  - openpyxl=3.0.10=py39hb9d737c_1
  - openssl=1.1.1t=h0b41bf4_0
  - packaging=21.3=pyhd8ed1ab_0
  - pandas=1.4.3=py39h1832856_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pcre=8.45=h9c3ff4c_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=9.2.0=py39hd5dbb17_2
  - pip=22.2.2=pyhd8ed1ab_0
  - ply=3.11=py_1
  - portaudio=19.6.0=h8e90077_6
  - prettytable=3.4.1=pyhd8ed1ab_0
  - prompt-toolkit=3.0.31=pyha770c72_0
  - psutil=5.9.2=py39hb9d737c_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pulseaudio=14.0=h0868958_9
  - pure-sasl=0.6.2=pyhd8ed1ab_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.13.0=pyhd8ed1ab_0
  - pyhive=0.6.5=pyhd8ed1ab_0
  - pymssql=2.2.5=py39h5a03fae_1
  - pymysql=1.0.3=pyhd8ed1ab_0
  - pyodbc=4.0.34=py39h5a03fae_0
  - pyopenssl=22.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyqt=5.15.7=py39h18e9c17_0
  - pyqt5-sip=12.11.0=py39h5a03fae_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.9.13=h9a8a25e_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytz=2022.2.1=pyhd8ed1ab_0
  - pyzmq=24.0.0=py39headdf64_0
  - qt-main=5.15.6=hc525480_0
  - readline=8.1.2=h0f457ee_0
  - requests=2.28.1=pyhd8ed1ab_1
  - setuptools=65.3.0=pyhd8ed1ab_1
  - sip=6.6.2=py39h5a03fae_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlalchemy=1.4.39=py39hb9d737c_0
  - sqlite=3.39.3=h4ff8645_0
  - sqlparse=0.4.2=pyhd8ed1ab_0
  - stack_data=0.5.0=pyhd8ed1ab_0
  - thrift=0.16.0=py39h5a03fae_1
  - thrift_sasl=0.4.3=pyhd8ed1ab_1
  - tk=8.6.12=h27826a3_0
  - toml=0.10.2=pyhd8ed1ab_0
  - tornado=6.2=py39hb9d737c_0
  - traitlets=5.4.0=pyhd8ed1ab_0
  - tzdata=2022c=h191b570_0
  - unicodedata2=14.0.0=py39hb9d737c_1
  - unixodbc=2.3.10=h583eb01_0
  - urllib3=1.26.11=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - wheel=0.37.1=pyhd8ed1ab_0
  - xcb-util=0.4.0=h166bdaf_0
  - xcb-util-image=0.4.0=h166bdaf_0
  - xcb-util-keysyms=0.4.0=h166bdaf_0
  - xcb-util-renderutil=0.3.9=h166bdaf_0
  - xcb-util-wm=0.4.1=h166bdaf_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.6=h166bdaf_0
  - zeromq=4.3.4=h9c3ff4c_1
  - zipp=3.8.1=pyhd8ed1ab_0
  - zlib=1.2.12=h166bdaf_3
  - zstd=1.5.2=h6239696_4
  - pip:
      - aiobotocore==2.5.0
      - aiohttp==3.8.4
      - aioitertools==0.11.0
      - aiosignal==1.3.1
      - asciitree==0.3.3
      - async-timeout==4.0.2
      - attrs==22.1.0
      - botocore==1.29.76
      - cftime==1.6.2
      - click==8.1.3
      - click-plugins==1.1.1
      - cligj==0.7.2
      - fasteners==0.18
      - fiona==1.9.3
      - fire==0.4.0
      - fontmeta==1.6.1
      - frozenlist==1.3.3
      - fsspec==2023.4.0
      - geopandas==0.12.2
      - iniconfig==1.1.1
      - jmespath==1.0.1
      - matplotlib==3.3.0
      - mplfonts==0.0.7
      - multidict==6.0.4
      - munch==2.5.0
      - netcdf4==1.6.3
      - numcodecs==0.11.0
      - pluggy==0.13.1
      - py==1.11.0
      - pyproj==3.5.0
      - pytest==6.2.4
      - s3fs==0.4.2
      - shapely==2.0.1
      - termcolor==1.1.0
      - typing-extensions==4.5.0
      - wis-s3api==0.0.7
      - wrapt==1.15.0
      - xarray==2023.3.0
      - yarl==1.8.2
      - zarr==2.14.2
prefix: /opt/conda/envs/db-base
