dataset:
  input_path: "/home/fanyunkai/FYK_data/original_dataset/"
  output_path: "/home/fanyunkai/FYK_data/processed_dataset2.5/"
  files: []
  variables: ["æ€»æ°®"]

WQ_data:
  input_file1: "/home/fanyunkai/FYK_data/processed_dataset2.5/WQ_hanjiang.npy"
  input_file2: "/home/fanyunkai/FYK_data/processed_dataset2.5/WQ_hanjiang_binary.npy"
  dropout_rate: 0.2  
  random_seed: 77  